name: CMake on Linux with GCC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]
        c_compiler: [gcc]
        cpp_compiler: [g++]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      id: setup_python
      with:
        python-version: '3.10'
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Restore cached virtualenv
      uses: actions/cache/restore@v4
      id: restore_cache
      with:
        key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
        path: .venv
    
    - name: Setup environment
      shell: bash
      run: |
        chmod +x ./tools/setup/setup.sh 
        source ./tools/setup/setup.sh
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
      working-directory: ${{ github.workspace }}
    
    - name: Saved cached virtualenv
      uses: actions/cache/save@v4
      if: steps.restore_cache.outputs.cache-hit != 'true'
      with:
        key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
        path: .venv
    - name: Configure CMake

      shell: bash
      run: >
        Python3_ROOT_DIR= cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_C_FLAGS="-g -O0 --coverage -ftest-coverage -fprofile-arcs -fprofile-exclude-files=./tests/*"
        -DCMAKE_CXX_FLAGS="-g -O0 --coverage -ftest-coverage -fprofile-arcs -fprofile-exclude-files=./tests/*"
        -DCMAKE_EXE_LINKER_FLAGS="--coverage"
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      shell: bash
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      shell: bash
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        gcov_include: 'build/*'
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: vhexl/c_common_template
